import { Component, OnInit, OnDestroy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Router, ActivatedRoute } from '@angular/router';
import { Subject, of } from 'rxjs';
import { takeUntil, timeout, catchError, finalize } from 'rxjs/operators';
import { API_CONFIG } from '../core/api.config';
import { PassStateService } from '../services/pass-state.service';
import { AuthService } from '../core/auth.service';

const HTTP_TIMEOUT_MS = 12000;

// Document Details Model
export interface PassDocument {

  documentId: number | null;

  documentType: string;

  documentNo: string;

  expiryDate: string;

  fileKey: string;

  fileName: string;

  file: File | null;

  existingFile?: string;
}


// Pass History Model
export interface HistoryRecord {

  // Primary Key (Generated by Database)
  id?: number;

  // Vehicle Pass Number
  passNo: string;

  // Employee Code who performed the action
  empCode: string;

  // Workflow Action
  action: string;

  // User Remark
  remark: string;

  // Date & Time of Action
  dateOfEntry: string;
}


// Employee Lookup Response Model
export interface EmployeeLookupResponse {

  // Employee Number (EC No)
  employeeNo?: string;

  // Employee Name
  name?: string;

  // Department Code
  deptCode?: string;

  // Department Name
  deptName?: string;

  // Contractor Code
  contractorCode?: string;

  // Contractor Name
  contractorName?: string;

  // Aadhaar Number
  aadhaarNo?: string;

  // Employee Type (HEG, TACC, CONTRACT, CRE-PRM)
  empType?: string;
}


export interface PassRequest {
  id: number | null;
  passNo: number | null;

  vehicleNo: string;
  vehicleType: string;
  brandModel: string;

  employeeNo: string;
  empType: string;
  contractorCode: string | null;

  gateNo: string;
  parkingToBeUsed: string;

  status: string;
  remark: string | null;
  enterBy: string;

  documents: PassDocument[];
}


export interface PassRegistryResponseDTO {

  id: number;

  vehicleNo: string;

  vehicleType: string;

  brandModel: string;

  employeeNo: number;

  empType: string;

  contractorCode: string;

  gateNo: string;

  parkingToBeUsed: string;

  enterBy: string;

  enterDate: string;

  reqStatus: string;

  passNo: number;

  documents: PassDocument[];
}


// Pass Status Constants
export const PassStatus = {

  DRAFT: 'DRAFT',
  SAVED: 'SAVED',
  SUBMITTED: 'SUBMITTED',
  CONFIRMED: 'CONFIRMED',
  APPROVED: 'APPROVED',
  REGRET: 'REGRET',
  MODIFY: 'MODIFY',
  NEEDS_MODIFICATION: 'NEEDS_MODIFICATION'

} as const;


const ALLOWED_DOC_TYPES = ['RC', 'INSURANCE', 'LICENSE'];


/**
 * Creates an empty document object.
 * Used when the user clicks the "Add Document" button.
 */
function emptyDocument(): PassDocument {

  return {

    documentId: null,

    documentType: '',

    documentNo: '',

    expiryDate: '',

    fileKey: '',

    fileName: '',

    file: null,

    existingFile: ''

  };

}

type EmployeeType =
  | ''
  | 'HEG'
  | 'TACC'
  | 'CONTRACT'
  | 'CRE-PRM';


@Component({

  selector: 'app-pass-entry',

  standalone: true,

  imports: [
    CommonModule,
    FormsModule
  ],

  templateUrl: './pass-entry.html',

  styleUrl: './pass-entry.css'

})


export class PassEntry implements OnInit, OnDestroy {
  //=====================================================
  // Constants
  //=====================================================

  protected readonly ALLOWED_DOC_TYPES = ALLOWED_DOC_TYPES;



  readonly PassStatus = PassStatus;

  private readonly destroy$ = new Subject<void>();


  //=====================================================
  // HTTP Headers
  //=====================================================

  private readonly HEADERS = new HttpHeaders({
    'x-api-key': API_CONFIG.API_KEY,

  });




  //=====================================================
  // Vehicle Details (Two-Way Binding)
  //=====================================================

  vehicleNo: string = '';

  vehicleType: string = '';

  brandModel: string = '';


  //=====================================================
  // Employee Details (Two-Way Binding)
  //=====================================================

  employeeNo: string = '';

  ecNo: string = '';

  empType = signal<EmployeeType>('');

  contractorCode: string | null = null;


  //=====================================================
  // Gate & Parking
  //=====================================================

  gateNo: string = '';

  parkingToBeUsed: string = '';


  //=====================================================
  // Workflow
  //=====================================================

  status: string = PassStatus.DRAFT;

  remark: string | null = null;

  enterBy: string = '';


  // ADD HERE
  get currentStatus(): string {
    return (this.status ?? '').toUpperCase();
  }

  //=====================================================
  // Auto Filled Employee Details
  //=====================================================


  empName = signal<string>('');

  empDept = signal<string>('');

  empDeptCode = signal<string>('');

  empType_display = signal<string>('');

  empAadhar = signal<string>('');

  empContractorCode = '';

  empContractorName = '';

  contractorName = '';

  contractorEmail = '';

  empEmail = '';

  empSalary = '';

  empContractorEmail = '';


  //=====================================================
  // Document Details
  //=====================================================

  documents = signal<PassDocument[]>([
    emptyDocument()
  ]);


  //=====================================================
  // UI Signals
  //=====================================================



  // Database Primary Key
  registryId: number | null = null;

  // Vehicle Pass Number (Manual Entry)
  passNo: number | null = null;

  fetchingEmployee = signal<boolean>(false);

  empFetchError = signal<string>('');

  isSaving = signal<boolean>(false);

  saved = signal<boolean>(false);

  saveSuccess = signal<string>('');

  saveError = signal<string>('');


  //=====================================================
  // Screen Mode
  //=====================================================

  isModificationMode = signal<boolean>(false);

  isViewMode = signal<boolean>(false);



  isApproverMode = signal<boolean>(false);

  isConfirmerMode = signal<boolean>(false);


  //=====================================================
  // Workflow Signals
  //=====================================================



  modificationRemark = signal<string>('');

  reviewRemark = signal<string>('');

  isWorkflowSubmitting = signal<boolean>(false);


  //=====================================================
  // Pass History
  //=====================================================

  showPassHistory = signal<boolean>(false);

  isLoadingPassHistory = signal<boolean>(false);

  passHistoryError = signal<string>('');

  passHistory = signal<HistoryRecord[]>([]);


  //=====================================================
  // Private Variables
  //=====================================================

  private empData: EmployeeLookupResponse | null = null;

  private savedVehicleId: number | null = null;

  private savedPassRegistryId: number | null = null;

  private draftPassId: string | null = null;



  constructor(
    private http: HttpClient,
    private router: Router,
    private route: ActivatedRoute,
    private passState: PassStateService,
    private auth: AuthService
  ) { }

  get todayDate(): string {
    return new Date().toISOString().split('T')[0];
  }
  get isReadOnlyMode(): boolean {

    return !this.canEdit();

  }


  isEcNoLocked: boolean = false;


  //=====================================================
  // Angular Lifecycle Hook
  //=====================================================
  //=====================================================
  // Angular Life Cycle Hook
  //=====================================================
  ngOnInit(): void {


    //=====================================================
    // Load Logged User
    //=====================================================

    this.loadLoggedInUser();



    //=====================================================
    // Initialize Documents
    //=====================================================

    if (this.documents().length === 0) {

      this.documents.set([
        emptyDocument()
      ]);

    }



    //=====================================================
    // Check User Role
    //=====================================================

    const session = sessionStorage.getItem('vpsm_session');


    if (session) {

      try {

        const user = JSON.parse(session);


        const role = String(
          user.role ?? ''
        ).toUpperCase();



        console.log(
          "LOGIN ROLE : ",
          role
        );



        if (role === 'APPROVER') {

          this.isApproverMode.set(true);

        }
        else {

          // Default uploader
          this.isApproverMode.set(false);

        }



        console.log(
          "Approver Mode : ",
          this.isApproverMode()
        );


      }
      catch (error) {

        console.error(
          "Session parsing error",
          error
        );

        this.isApproverMode.set(false);

      }

    }




    //=====================================================
    // Route Handling
    //=====================================================

    this.route.queryParams
      .pipe(
        takeUntil(this.destroy$)
      )
      .subscribe(params => {

        const mode = String(params['mode'] ?? '').toLowerCase();
        const id = params['id'];

        console.log(
          "Mode : ",
          mode
        );

        console.log(
          "ID : ",
          id
        );

        //=================================================
        // View Mode
        //=================================================
        this.isViewMode.set(mode === 'view');

        //=================================================
        // Approver Mode
        //=================================================
        this.isApproverMode.set(mode === 'approver');

        //=================================================
        // Edit / View Existing Pass
        //=================================================
        if (
          (mode === 'edit' || mode === 'view')
          &&
          id
        ) {

          this.registryId = Number(id);

          console.log(
            "Loading Pass ID : ",
            this.registryId
          );

          this.loadPass(
            this.registryId
          );

        }
        else {

          // New Entry
          this.registryId = null;
          this.status = PassStatus.DRAFT;
        }

      });


  }

  //=====================================================
  // Load Existing Pass Details
  //=====================================================


  //=====================================================
  // Load Logged-in User Details
  //=====================================================
  private loadLoggedInUser(): void {

    const session = sessionStorage.getItem('vpsm_session');

    console.log(
      'vpsm_session = ',
      session
    );


    if (!session) {
      console.log('No session found');
      return;
    }


    try {

      const user = JSON.parse(session);


      console.log(
        'Logged User = ',
        user
      );


      // Employee code
      this.enterBy = user.empCode ?? '';



      // Role check
      const role = String(
        user.role ?? ''
      ).toUpperCase();



      console.log(
        'Login Role = ',
        role
      );



      if (role === 'APPROVER') {

        this.isApproverMode.set(true);

      }
      else {

        // Uploader
        this.isApproverMode.set(false);

      }



    } catch (error) {

      console.error(
        'Unable to parse session.',
        error
      );

    }

  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }



  //=====================================================
  // SECTION 6 : Utility Methods
  //=====================================================

  onUpperInput(event: Event, field: keyof PassEntry): void {
    if (this.isReadOnlyMode) return;
    const input = event.target as HTMLInputElement;
    const val = input.value.toUpperCase().replace(/\s+/g, '');
    (this as any)[field] = val;
    input.value = val;
  }




  onVehicleTypeInput(event: Event): void {
    if (this.isReadOnlyMode) return;

    const input = event.target as HTMLInputElement;
    this.vehicleType = this.formatUpperCase(input.value);
    input.value = this.vehicleType;
  }

  /**
   * Converts the input text to uppercase.
   * Example:
   *   "ab 12 cd" -> "AB 12 CD"
   */
  private formatUpperCase(value: string): string {
    return value.toUpperCase();
  }


  onDocNoInput(event: Event, doc: PassDocument): void {
    if (this.isReadOnlyMode) return;

    const input = event.target as HTMLInputElement;

    doc.documentNo = this.formatUpperCase(input.value);
    input.value = doc.documentNo;
  }


  shortName(name: string): string {
    return name.length > 18 ? name.substring(0, 15) + '...' : name;
  }


  formatDateDDMMYYYY(isoDate: string): string {
    if (!isoDate || isoDate.length < 10) return isoDate ?? '';
    const [y, m, d] = isoDate.split('-');
    return `${d}/${m}/${y}`;
  }



  formatDateTime(d: string): string {
    if (!d) return '—';
    const dt = new Date(d);
    if (isNaN(dt.getTime())) return d;

    const date = dt.toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric'
    });

    const time = dt.toLocaleTimeString('en-IN', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });

    return `${date}, ${time}`;
  }


  openDatePicker(input: HTMLInputElement): void {
    try { (input as any).showPicker(); } catch { input.click(); }
  }



  //=====================================================
  // SECTION 7 : Employee Methods
  //=====================================================




  loadEmployee(): void {

    this.empFetchError.set('');
    this.clearEmployeeData();
    this.fetchingEmployee.set(true);

    const url = `${API_CONFIG.EMPLOYEE_REPORT}/${encodeURIComponent(this.employeeNo)}`;

    this.http.get<any>(url, { headers: this.HEADERS })
      .pipe(
        timeout(HTTP_TIMEOUT_MS),
        takeUntil(this.destroy$),
        catchError(err => {
          this.empFetchError.set(
            `Could not fetch employee details (${err?.status ?? 'Network Error'})`
          );
          return of(null);
        }),
        finalize(() => this.fetchingEmployee.set(false))
      )
      .subscribe(res => {

        if (!res) return;

        const selectedType = this.empType().trim().toUpperCase();
        const apiType = String(res.empType || '').trim().toUpperCase();

        if (selectedType !== apiType) {
          this.clearEmployeeData();

          this.empFetchError.set(
            `Employee Type mismatch. Selected: ${selectedType}, Found: ${apiType}`
          );
          return;
        }

        this.empData = res;

        this.empName.set(String(res.name || ''));
        this.empDept.set(String(res.deptName || '').toUpperCase());
        this.empDeptCode.set(String(res.deptCode || ''));
        this.empAadhar.set(String(res.aadhaarNo || res.aadharNo || ''));

        this.empType_display.set(apiType);

        this.empContractorCode = String(res.contractorCode || '');

        // IMPORTANT: value used in payload
        this.contractorCode = String(res.contractorCode || '');

        this.empContractorName = String(res.contractorName || '');


        this.empFetchError.set('');
      });
  }


  private clearEmployeeData(): void {

    this.empData = null;

    this.empName.set('');
    this.empDept.set('');
    this.empDeptCode.set('');
    this.empAadhar.set('');
    this.empType_display.set('');

    this.empContractorCode = '';
    this.empContractorName = '';
    this.contractorName = '';
    this.contractorEmail = '';
  }



  //=====================================================
  // SECTION 8 : Document Methods
  //=====================================================

  addDocument(): void {
    if (this.isReadOnlyMode) return;

    const docs = [...this.documents()];

    // Prevent adding another row if the last one is incomplete
    const lastDoc = docs[docs.length - 1];

    if (
      !lastDoc.documentType ||
      !lastDoc.documentNo ||
      !lastDoc.expiryDate
    ) {
      alert('Please complete the current document before adding a new one.');
      return;
    }

    docs.push(emptyDocument());

    this.documents.set(docs);
  }



  removeDocument(index: number): void {
    if (this.isReadOnlyMode) return;

    this.documents.update(docs => {
      if (docs.length === 1) {
        return docs; // Keep at least one row
      }

      return docs.filter((_, i) => i !== index);
    });
  }

  removeDoc(index: number): void {

    this.removeDocument(index);

  }


  availableDocTypes(index: number): string[] {
    const docs = this.documents();

    const selectedTypes = docs
      .filter((_, i) => i !== index)
      .map(doc => doc.documentType)
      .filter(type => !!type);

    return ALLOWED_DOC_TYPES.filter(type =>
      !selectedTypes.includes(type) || docs[index].documentType === type
    );
  }


  onDocumentTypeChange(index: number, documentType: string): void {
    if (this.isReadOnlyMode) return;

    this.documents.update(docs => {
      const updatedDocs = [...docs];

      updatedDocs[index] = {
        ...updatedDocs[index],
        documentType,
        documentNo: '',
        expiryDate: '',
        file: null,
        fileName: '',
        fileKey: '',
        existingFile: ''
      };

      return updatedDocs;
    });
  }


  onDocumentFileSelected(event: Event, index: number): void {

    if (this.isReadOnlyMode) return;


    const input = event.target as HTMLInputElement;


    if (!input.files || input.files.length === 0) {
      return;
    }


    const file = input.files[0];


    // File Size Validation
    const maxSize = 5 * 1024 * 1024;

    if (file.size > maxSize) {

      alert('File size must be less than 5 MB.');

      input.value = '';

      return;
    }



    // File Type Validation
    const allowedTypes = [
      'application/pdf',
      'image/jpeg',
      'image/png'
    ];


    if (!allowedTypes.includes(file.type)) {

      alert('Only PDF, JPG and PNG files are allowed.');

      input.value = '';

      return;
    }



    this.documents.update(docs => {

      const updated = [...docs];


      updated[index] = {

        ...updated[index],

        file: file,

        fileName: file.name,

        // IMPORTANT
        fileKey: `document_${index}`

      };


      console.log(
        'Updated Document List:',
        updated
      );


      return updated;

    });


    // Clear input for next selection
    input.value = '';

  }





  //=====================================================
  // SECTION 9 : Validation
  //=====================================================

  private validateVehicle(): boolean {

    if (!this.vehicleNo.trim()) {
      this.saveError.set('Vehicle Number is required.');
      return false;
    }

    if (!this.vehicleType.trim()) {
      this.saveError.set('Vehicle Type is required.');
      return false;
    }

    if (!this.brandModel.trim()) {
      this.saveError.set('Brand / Model is required.');
      return false;
    }

    return true;
  }


  private validateDocuments(): boolean {

    const docs = this.documents();

    if (docs.length === 0) {
      this.saveError.set('Please add at least one document.');
      return false;
    }

    for (let i = 0; i < docs.length; i++) {

      const doc = docs[i];

      if (!doc.documentType) {
        this.saveError.set(`Please select Document Type for row ${i + 1}.`);
        return false;
      }

      if (!doc.documentNo.trim()) {
        this.saveError.set(`Please enter Document Number for row ${i + 1}.`);
        return false;
      }

      if (!doc.expiryDate) {
        this.saveError.set(`Please select Expiry Date for row ${i + 1}.`);
        return false;
      }

      // For a new record, file is mandatory.
      // During edit, an existing file is acceptable.
      if (!doc.file && !doc.existingFile) {
        this.saveError.set(`Please upload a file for row ${i + 1}.`);
        return false;
      }
    }

    return true;
  }




  private validateEmployee(): boolean {

    if (!this.empType()) {
      this.saveError.set('Please select Employee Type.');
      return false;
    }

    if (!this.employeeNo.trim()) {
      this.saveError.set('Employee Code is required.');
      return false;
    }

    if (!this.empName()) {
      this.saveError.set('Please verify Employee Code.');
      return false;
    }

    return true;
  }


  private validateGateAndParking(): boolean {

    if (!this.gateNo.trim()) {
      this.saveError.set('Gate No is required.');
      return false;
    }

    if (!this.parkingToBeUsed.trim()) {
      this.saveError.set('Parking To Be Used is required.');
      return false;
    }

    return true;
  }



  //=====================================================
  // SECTION 10 : Build Request
  //=====================================================


  private buildRequest(): PassRequest {

    const payload: PassRequest = {

      id: this.registryId,

      passNo: this.passNo,


      // Vehicle Details
      vehicleNo: this.vehicleNo?.trim() ?? '',

      vehicleType: this.vehicleType?.trim() ?? '',

      brandModel: this.brandModel?.trim() ?? '',



      // Employee Details
      employeeNo: this.employeeNo?.trim() ?? '',

      empType: this.empType(),

      contractorCode: this.contractorCode,



      // Gate Parking
      gateNo: this.gateNo?.trim() ?? '',

      parkingToBeUsed: this.parkingToBeUsed?.trim() ?? '',



      // Workflow
      status: this.status,

      remark: this.remark,

      enterBy: this.enterBy,



      // Documents
      documents: this.documents()

    };


    console.log(
      '========= PASS FORM PAYLOAD ========='
    );

    console.log(
      JSON.stringify(payload, null, 2)
    );

    console.log("CONTRACTOR CODE FROM FORM ===>", this.contractorCode);




    return payload;
  }



  private buildFormData(): FormData {

    const formData = new FormData();

    // Request JSON
    formData.append(
      'request',
      new Blob(
        [JSON.stringify(this.buildRequest())],
        { type: 'application/json' }
      )
    );

    // Document files
    this.documents().forEach(doc => {
      if (doc.file) {
        formData.append(doc.fileKey, doc.file, doc.file.name);
        for (const pair of (formData as any).entries()) {
          console.log(pair[0], pair[1]);
        }
      }
    });

    return formData;
  }



  //=====================================================
  // SECTION 11 : CRUD Operations
  //=====================================================

  savePass(): void {

    if (this.isReadOnlyMode) {
      return;
    }

    this.saveError.set('');
    this.saveSuccess.set('');

    if (!this.validateForm()) {
      return;
    }

    this.isSaving.set(true);

    const formData = this.buildFormData();

    //=========================
    // EDIT MODE
    //=========================
    if (this.registryId != null) {

      this.http.put<PassRegistryResponseDTO>(
        `${API_CONFIG.PASS_UPDATE}/${this.registryId}`,
        formData,
        { headers: this.HEADERS }
      )
        .pipe(
          timeout(HTTP_TIMEOUT_MS),
          takeUntil(this.destroy$),
          finalize(() => this.isSaving.set(false))
        )
        .subscribe({

          next: (response) => {

            this.saved.set(true);
            this.saveSuccess.set('Vehicle pass updated successfully.');

            this.registryId = response.id;
            this.passNo = response.passNo;
            this.status = response.reqStatus;

          },

          error: (err) => {

            this.saveError.set(
              err?.error?.message ?? 'Unable to update vehicle pass.'
            );

          }

        });

      return;
    }

    //=========================
    // ADD MODE
    //=========================
    this.http.post<PassRegistryResponseDTO>(
      API_CONFIG.PASS_SAVE,
      formData,
      { headers: this.HEADERS }
    )
      .pipe(
        timeout(HTTP_TIMEOUT_MS),
        takeUntil(this.destroy$),
        finalize(() => this.isSaving.set(false))
      )
      .subscribe({

        next: (response) => {

          this.saved.set(true);
          this.saveSuccess.set('Vehicle pass saved successfully.');

          this.registryId = response.id;
          this.passNo = response.passNo;
          this.status = response.reqStatus;

        },

        error: (err) => {

          this.saveError.set(
            err?.error?.message ?? 'Unable to save vehicle pass.'
          );

        }

      });

  }



  updatePass(): void {

    if (this.isReadOnlyMode) {
      return;
    }

    if (!this.registryId) {
      this.saveError.set('Invalid Pass ID.');
      return;
    }

    this.saveError.set('');
    this.saveSuccess.set('');

    if (!this.validateForm()) {
      return;
    }

    this.isSaving.set(true);

    const formData = this.buildFormData();

    this.http.put<PassRegistryResponseDTO>(
      `${API_CONFIG.PASS_UPDATE}/${this.registryId}`,
      formData,
      { headers: this.HEADERS }
    )
      .pipe(
        timeout(HTTP_TIMEOUT_MS),
        takeUntil(this.destroy$),
        finalize(() => this.isSaving.set(false))
      )
      .subscribe({
        next: (response) => {

          this.registryId = response.id;
          this.passNo = response.passNo;
          this.status = response.reqStatus;

          this.saved.set(true);
          this.saveSuccess.set('Vehicle pass updated successfully.');
        },

        error: (err) => {
          this.saveError.set(
            err?.error?.message ?? 'Unable to update vehicle pass.'
          );
        }
      });
  }



  private loadPass(id: number): void {

    this.isSaving.set(true);
    this.saveError.set('');

    this.http.get<PassRegistryResponseDTO>(
      `${API_CONFIG.PASS_LIST}/${id}`,
      {
        headers: this.HEADERS
      }
    )
      .pipe(
        timeout(HTTP_TIMEOUT_MS),
        takeUntil(this.destroy$),
        finalize(() => this.isSaving.set(false))
      )
      .subscribe({

        next: (response) => {

          //=====================================================
          // Primary Details
          //=====================================================

          this.registryId = response.id;

          this.passNo = response.passNo;


          //=====================================================
          // Vehicle Details
          //=====================================================

          this.vehicleNo = response.vehicleNo ?? '';

          this.vehicleType = response.vehicleType ?? '';

          this.brandModel = response.brandModel ?? '';


          //=====================================================
          // Employee Details
          //=====================================================

          this.employeeNo = String(response.employeeNo ?? '');

          this.ecNo = String(response.employeeNo ?? '');

          this.setEmployeeType(response.empType);

          this.contractorCode = response.contractorCode ?? null;


          //=====================================================
          // Gate & Parking
          //=====================================================

          this.gateNo = response.gateNo ?? '';

          this.parkingToBeUsed = response.parkingToBeUsed ?? '';


          //=====================================================
          // Workflow
          //=====================================================

          this.status = response.reqStatus ?? PassStatus.DRAFT;

          this.enterBy = response.enterBy ?? '';


          //=====================================================
          // Documents
          //=====================================================

          if (response.documents && response.documents.length > 0) {

            this.documents.set(

              response.documents.map(doc => ({

                documentId: doc.documentId ?? null,

                documentType: doc.documentType ?? '',

                documentNo: doc.documentNo ?? '',

                expiryDate: doc.expiryDate ?? '',

                fileKey: doc.fileKey ?? '',

                fileName: doc.fileName ?? '',

                // Keep old file name during update
                existingFile: doc.fileName ?? '',

                // Browser cannot preload file
                file: null

              }))

            );

          } else {

            // Add blank row if no documents exist

            this.documents.set([
              emptyDocument()
            ]);

          }



          //=====================================================
          // UI State
          //=====================================================

          this.saved.set(true);

          this.saveSuccess.set('Pass details loaded successfully.');


          //=====================================================
          // Load employee details (Name, Dept, Aadhar etc.)
          //=====================================================

          if (this.employeeNo) {
            this.loadEmployee();
          }

        },

        error: (error) => {

          console.error('Load Pass Error:', error);

          this.saveError.set(
            error?.error?.message ??
            'Unable to load pass details.'
          );

        }

      });

  }


  private setEmployeeType(type: string | null | undefined): void {

    const value = (type ?? '').toUpperCase();

    if (
      value === 'HEG' ||
      value === 'TACC' ||
      value === 'CONTRACT' ||
      value === 'CRE-PRM'
    ) {
      this.empType.set(value);
    } else {
      this.empType.set('');
    }
  }







  //=====================================================
  // SECTION 12 : Workflow
  //=====================================================

  updatePassStatus(id: number, status: string): void {

    this.isSaving.set(true);

    const payload = {

      status: status,

      remark: this.reviewRemark(),

      enterBy: this.enterBy

    };

    this.http.put<any>(
      `${API_CONFIG.PASS_STATUS_UPDATE}/${id}`,
      payload,
      {
        headers: this.HEADERS
      }
    ).subscribe({

      next: (response) => {

        this.isSaving.set(false);

        console.log("Status Updated Successfully", response);

        // Refresh data
        this.loadPass(id);

        // Optional notification
        this.showMessage(
          `${status} completed successfully`
        );
      },

      error: (error) => {

        this.isSaving.set(false);

        console.error("Status update failed", error);

        this.showMessage(
          "Status update failed"
        );
      }
    });
  }




  confirmPass(): void {
    if (!this.registryId) return;

    this.updatePassStatus(
      this.registryId,
      PassStatus.CONFIRMED
    );
  }


  approvePass(): void {
    if (!this.registryId) return;

    this.updatePassStatus(
      this.registryId,
      PassStatus.APPROVED
    );
  }


  regretPass(): void {
    if (!this.registryId) return;

    this.updatePassStatus(
      this.registryId,
      PassStatus.REGRET
    );
  }


  modifyPass(): void {
    if (!this.registryId) return;

    this.updatePassStatus(
      this.registryId,
      PassStatus.MODIFY
    );
  }

  private showMessage(message: string): void {
    alert(message);
  }


  //=====================================================
  // Employee Type Change
  //=====================================================

  onEmpTypeChange(value: EmployeeType): void {

    this.empType.set(value);

    // Clear previous employee details
    this.clearEmployeeData();

    // Clear employee code
    this.employeeNo = '';

    this.empFetchError.set('');

  }

  canEdit(): boolean {

    return (
      this.status === PassStatus.DRAFT ||
      this.status === PassStatus.SAVED ||
      this.status === PassStatus.MODIFY||
      this.status === PassStatus.NEEDS_MODIFICATION
      
    );

  }


  onEcNoBlur(): void {

    if (!this.empType()) {

      this.empFetchError.set(
        'Please select Employee Type first'
      );

      return;
    }


    if (!this.ecNo || this.ecNo.trim() === '') {
      return;
    }


    // Copy HTML field value to API variable
    this.employeeNo =
      this.ecNo.trim().toUpperCase();


    this.loadEmployee();

  }

  onSubmit(): void {
    console.log("===== SUBMIT CLICKED =====");

    this.status = PassStatus.CONFIRMED;

    console.log(
      "STATUS BEFORE SAVE = ",
      this.status
    );

    if (!this.validateForm()) {
      return;
    }

    this.isSaving.set(true);
    this.saveError.set('');
    this.saveSuccess.set('');

    const formData = this.buildFormData();

    if (this.registryId != null) {
      console.log(
        "UPDATE MODE ID = ",
        this.registryId
      );

      this.http.put<PassRegistryResponseDTO>(
        `${API_CONFIG.PASS_UPDATE}/${this.registryId}`,
        formData,
        { headers: this.HEADERS }
      )
        .pipe(
          timeout(HTTP_TIMEOUT_MS),
          takeUntil(this.destroy$),
          finalize(() => this.isSaving.set(false))
        )
        .subscribe({
          next: (response) => {
            this.saved.set(true);
            this.registryId = response.id;
            this.passNo = response.passNo;
            this.status = response.reqStatus;
            this.saveSuccess.set('Vehicle pass submitted successfully.');
          },
          error: (err) => {
            this.saveError.set(
              err?.error?.message ?? 'Unable to submit vehicle pass.'
            );
          }
        });

      return;
    }

    console.log("SAVE MODE");

    this.http.post<PassRegistryResponseDTO>(
      API_CONFIG.PASS_SAVE,
      formData,
      { headers: this.HEADERS }
    )
      .pipe(
        timeout(HTTP_TIMEOUT_MS),
        takeUntil(this.destroy$),
        finalize(() => this.isSaving.set(false))
      )
      .subscribe({
        next: (response) => {
          this.saved.set(true);
          this.registryId = response.id;
          this.passNo = response.passNo;
          this.status = response.reqStatus;
          this.saveSuccess.set('Vehicle pass submitted successfully.');
        },
        error: (err) => {
          this.saveError.set(
            err?.error?.message ?? 'Unable to submit vehicle pass.'
          );
        }
      });
  }

  private validateForm(): boolean {

    console.log("VALIDATION START");

    this.saveError.set('');

    if (!this.validateVehicle()) {
      console.log("Vehicle validation failed");
      return false;
    }


    if (!this.validateEmployee()) {
      console.log("Employee validation failed");
      return false;
    }


    if (!this.validateGateAndParking()) {
      console.log("Gate validation failed");
      return false;
    }


    if (!this.validateDocuments()) {
      console.log("Document validation failed");
      return false;
    }


    console.log("VALIDATION SUCCESS");

    return true;
  }


  //=====================================================
  // STATUS CONTROL
  //=====================================================

  isNew(): boolean {
    return this.registryId === null;
  }


  isSavedStatus(): boolean {
    return this.status === PassStatus.SAVED;
  }


  isSubmittedStatus(): boolean {
    return this.status === PassStatus.SUBMITTED;
  }


  isConfirmedStatus(): boolean {
    return this.status === PassStatus.CONFIRMED;
  }


  isModifyStatus(): boolean {
    return this.status === PassStatus.MODIFY;
  }


  isApprovedStatus(): boolean {
    return this.status === PassStatus.APPROVED;
  }

  //=====================================================
  // SECTION 13 : History
  //=====================================================



  togglePassHistory(): void {

    const open = !this.showPassHistory();

    this.showPassHistory.set(open);


    if (
      open &&
      this.registryId &&
      this.passHistory().length === 0
    ) {

      this.loadPassHistory(this.registryId);

    }

  }

  private loadPassHistory(id: number): void {

    this.isLoadingPassHistory.set(true);

    this.passHistoryError.set('');


    this.http.get<HistoryRecord[]>(
      `${API_CONFIG.PASS_HISTORY}/${id}`,
      {
        headers: this.HEADERS
      }
    )
      .pipe(
        takeUntil(this.destroy$),
        finalize(() => this.isLoadingPassHistory.set(false))
      )
      .subscribe({

        next: (response) => {

          this.passHistory.set(response ?? []);

        },


        error: (err) => {

          console.error(err);

          this.passHistoryError.set(
            'Unable to load pass history.'
          );

        }

      });

  }
  //=====================================================
  // Navigation
  //=====================================================

  goBackToPasses(): void {

    if (window.history.length > 1) {

      this.router.navigate(['/pass-list']);

    } else {

      this.router.navigate(['/']);

    }

  }

}